
export const Tracks = {
  D1: [
    'Welcome to Portland',
    'Recovery',
    'Melanchol Shuffles',
    'The Merciful Heart (RIP Double-P)',
    'My Plan is Fucked',
    'Right Place Wrong Time',
    'Protean',
    'Alone with the Ghosts',
    'I Can&#39;t Sleep',
    'An Evening Theme for Zordak',
    'Throwbacks (Ben&#39;s Living Room)',
    'You&#39;ve Got Something',
    'Lust on Smash',
    'Low (J Dilla Tribute)',
    'Some Rollin Blues',
    'Couple Things to Know',
    'Spanish Swagger',
    'Right When You Give Up',
    'Show Me the Way',
    'Untitled 5 (...for the rain)',
    'GHA (We Are Doomed)',
    'This Shit Isn&#39;t Real',
    'Called the Business',
    'The Majestical',
    'Another Dream',
    'The Dance',
    'Tales From Teh Sippeh',
    'Shorty Pop (The One About Le Screw)',
    'Emotional Content',
    'Sincurrleh',
    'SE Hawthorne',
    'Cruzat vs Fiasco (Superstar)'
  ],
  D2: [
    'Creative Thinkers Advance',
    'I Am The Man',
    'Plodd (Seaside Air)',
    'The Almost True Story of How We Fell In Love',
    'Lucky Guitar Strap',
    'Blood',
    'Cold Process of Elimination',
    'Morning Routine',
    'Bumped Up',
    'The Storm Breaks',
    'Obama Can&#39;t Walk On Water',
    'Bruh',
    'Daily Commute (Little Green Notebook)',
    'The Weird',
    'Downtemp',
    'Corporate Culture',
    'All Day',
    'Here We Go',
    'Fidelus',
    'Reflections',
    'The Law of the Corner',
    'I Never Saw It',
    'Hope You&#39;re Proud',
    'Still Climbing',
    'Calm in the Chase',
    'Electrocaine',
    'Bullshit Agency',
    'The Oasis is Real',
    'The Last Man (Stardust)',
    'So Glad It Never Happened',
    'The Seed of Menace',
    'Light Reign',
    'Sadness of Dusk (Shambles)',
    'Swanger',
    'The Knowing',
    'The End',
    'Eva &amp; Max',
    'Cruzat vs INXS (Questions)'
  ],
  D3: [
    'An Understatement to Say...',
    'A Stranger In the Missed',
    'The Haze',
    'Insomnia',
    'Sarcasm and Sincerity',
    'My Office in the Sky',
    'DWNVSKL (Return to Camp Bell)',
    'Bodega Chicken',
    'Do You Dream?',
    'This Is My Fuckin Dream',
    'Born of Kings',
    'The Girl on the Bus',
    'I&#39;m a 70&#39;s Baby, Baby',
    'Sticky Fingers',
    'Pressure Pier',
    'Came Up Sick',
    'They Needed Us',
    'I Was Selfish',
    'Ridiculous Chivalrous Posturing',
    'After the Soul',
    'Scared Ass Bitch',
    'Magellan',
    'Drink &amp; Write',
    'Ascetix (What Kind of Life?)',
    'Stakeout',
    'Losing Time',
    'Nose Fulla Coke',
    'The Whye',
    'Ellsworth',
    'The Art of Moneymaking (Layercake)',
    'The First Time I Saw Her',
    'Cruzat vs Fruition (For LL / Pump)'
  ],
  D4: [
    'Terrible Things',
    'An Earnest Plate of Cold',
    'Be On One',
    'Best in the Business',
    'Question Is',
    'Needs / Gets',
    'Salt Mine',
    'Buoyancy',
    'A Sultry Interlude',
    'Are We Solid?',
    'B Leav N U',
    'Junk Shop Digging',
    'Rush, Crash, Apathy',
    'Call to Prayer (DSHND)',
    'Ed Floated Away',
    'Drifting',
    'Menthols',
    'Not About That Life',
    'Mature Brags',
    'The Shaolin',
    'Foster Road Grifter',
    'Promise by the Pond',
    'Volume Pump',
    'Imperfect Paradise',
    'Neither or Nor',
    'All a Fugazie',
    'Brother Do the Math',
    'Disclaimer &amp; Definition',
    'White Boy',
    'My Last Night in Evanston',
    'Daze Between',
    'Stumptown (E+C Anthem)',
    'Back to the Dega',
    'Next Big Step',
    'Cruzat vs Erasure (Breath of Life)'
  ]
}
